### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '250.24' on /app/sales-invoice

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#140]
Can't confirm payment with decimal amount.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/2a73feaa-de26-4122-af6f-d32346b09b1e)

--

### App Versions
```
{
	"apps_maintainer": "0.0.1",
	"business_automations": "0.0.1",
	"erpnext": "15.6.0",
	"frappe": "15.5.0",
	"test_app": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2023-00005
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 71, in execute_cmd
    return run_server_script(server_script)
  File "apps/frappe/frappe/handler.py", line 89, in run_server_script
    response = frappe.get_doc("Server Script", server_script).execute_method()
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 150, in execute_method
    return execute_api_server_script(self)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 286, in execute_api_server_script
    _globals, _locals = safe_exec(script.script, script_filename=script.name)
  File "apps/frappe/frappe/utils/safe_exec.py", line 101, in safe_exec
    exec(
  File "<serverscript>: confirmpayment", line 15, in <module>
ValueError: invalid literal for int() with base 10: '250.24'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"sales_invoice": "ACC-SINV-2023-00005",
		"reference": "ACC-SINV-2023-00005",
		"mode_of_payment": "Cheque",
		"paid_amount": 250.24,
		"fields": "{\"paid_to\":\"Cash - Z\",\"payment_type\":\"Receive\",\"mode_of_payment\":\"Cheque\",\"party_type\":\"Customer\",\"target_exchange_rate\":1,\"party\":\"Muzammal rasool\",\"paid_amount\":250.24,\"received_amount\":48000}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/confirmPayment",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: invalid literal for int() with base 10: '250.24'",
	"exc_type": "ValueError",
	"_exc_source": "Server Script"
}
```

**Comment by Muzmal** [comment]
Fixed
