### ISSUE TITLE
TypeError: 'str' object does not support item assignment /app/customer

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/frappe#193]
Can't add a new customer.

![Image](https://github.com/zaviagodev/frappe/assets/120152434/96499be9-abbb-4c30-9a9f-39115aa0929e)

### App Versions
```
{
	"apps_maintainer": "0.0.1",
	"business_automations": "0.0.1",
	"e_commerce_store": "0.0.1",
	"erpnext": "15.7.0",
	"frappe": "15.11.0",
	"headless_e_commerce": "0.0.1",
	"payments": "0.0.1",
	"test_app": "0.0.1",
	"webshop": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-zyzviqmgkn
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 18, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 82, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 132, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 134, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 184, in update
    self.set(key, value, as_value=ignore_children)
  File "apps/frappe/frappe/model/base_document.py", line 236, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 294, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 262, in append
    ret_value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 307, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-zyzviqmgkn\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"chomchuen@zaviago.com\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"is_internal_customer\":0,\"companies\":[],\"custom_transactions_virtual_table\":[],\"language\":\"en\",\"credit_limits\":\"0\",\"accounts\":[],\"sales_team\":[],\"so_required\":0,\"dn_required\":0,\"is_frozen\":0,\"disabled\":0,\"portal_users\":[],\"represents_company\":\"\",\"customer_name\":\"chomch\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700135112064584592241": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 544,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'str' object does not support item assignment",
	"exc_type": "TypeError"
}
```

**Comment by deviljutt** [comment]
@primSirirnit Please check this

**Comment by chomchuen** [comment]
**Resolved.✅**

![Image](https://github.com/zaviagodev/frappe/assets/120152434/bb996b2e-00d5-41d3-b1ec-186fa9b10420)
